<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-13">

<title>Michael Li - Why Do the Arrows That Stay on the Same Line Matter So Much?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Michael Li</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../bio.html">
 <span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../resume.html">
 <span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../blog/index.html">
 <span class="menu-text">Blog</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Why Do the Arrows That Stay on the Same Line Matter So Much?</h1>
  <div class="quarto-categories">
    <div class="quarto-category">mathematics</div>
    <div class="quarto-category">data-science</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 13, 2026</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p>Eigenvalues and eigenvectors sound intimidating for some people who are not familiar with them. But actually the main idea starts with something simple: an arrow. When a matrix changes an arrow, some arrows stay on the same line. These are eigenvectors, and their eigenvalues describe how they are scaled.</p>
<p>This can be hard to see when a matrix is introduced as a box of numbers the first time we see one. We get busy multiplying entries and lose track of what the calculation does.</p>
<p>But even after I got the picture, one thing still bugged me quite a while. These arrows are actually pretty rare. If you take a typical matrix and apply it to a random arrow, the arrow almost always turns. In the plane, these special arrows fill at most two lines. And yet, eigenvectors seem to show up everythere in datascience. OCA uses them, Markov chains use them, and even Google’s original PageRank scores, which Google used to rank webpages, come from an eigenvector. Most explanations I’ve seen on textbooks focus on how to calculate those eigenvectors, not on why these few special arrows are such a big deal.</p>
<p>That is the question I want to figure out in my first blog post: if almost every arrow turns, what do the few arrows that don’t turn tell us about all the other ones? I’ll start with a small example and a picture that may make the idea easier to follow for you. Then we’ll do a little experiment in R and keep applying the sma matrix over and over, a bit like how a Markow chain moves forward one step at a time, and see where the turning arrows end up.</p>
<section id="a-small-example" class="level2">
<h2 class="anchored" data-anchor-id="a-small-example">A small example</h2>
<p>Let’s use this matrix as an example:</p>
<p><span class="math display">\[
A = \begin{pmatrix}2 &amp; 1 \\ 1 &amp; 2\end{pmatrix}.
\]</span></p>
<p>Think of a vector as an arrow starting at the origin. The vector <span class="math inline">\((1,1)\)</span> ends one unit right and one unit up. This R code applies the matrix to that arrow. The symbol <code>%*%</code> means matrix multiplication.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>), <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>A <span class="sc">%*%</span> v</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]
[1,]    3
[2,]    3</code></pre>
</div>
</div>
<p>The result is <span class="math inline">\((3,3)\)</span>. The arrow becomes three times as long, but still points along the same diagonal. That makes <span class="math inline">\((1,1)\)</span> an eigenvector of <span class="math inline">\(A\)</span>, with an eigenvalue of 3.</p>
<p>Eigenvectors can also have different lengths.For example, an arrow twice as long along this diagonal still gets stretched by three. Its starting size changes, but its eigenvalue stays the same because the scaling is unchanged.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="at">type =</span> <span class="st">"n"</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">3.5</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">3.5</span>),</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"x"</span>, <span class="at">ylab =</span> <span class="st">"y"</span>, <span class="at">asp =</span> <span class="dv">1</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">arrows</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">arrows</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="st">"Before"</span>, <span class="at">pos =</span> <span class="dv">2</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="st">"After"</span>, <span class="at">pos =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="blog1_post_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">The blue arrow is the original vector. The red arrow extends three times as far along the same line.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Now try <span class="math inline">\((1,0)\)</span>. This arrow starts out pointing horizontally.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>A <span class="sc">%*%</span> w</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]
[1,]    2
[2,]    1</code></pre>
</div>
</div>
<p>The result is <span class="math inline">\((2,1)\)</span>, so the arrow tilts upward. It changes direction, which means <span class="math inline">\((1,0)\)</span> is not an eigenvector of this matrix. The difference is easy to see: one arrow gets longer along its original line, while the other turns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="at">type =</span> <span class="st">"n"</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">3.5</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">3.5</span>),</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"x"</span>, <span class="at">ylab =</span> <span class="st">"y"</span>, <span class="at">asp =</span> <span class="dv">1</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">arrows</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">arrows</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="st">"Before"</span>, <span class="at">pos =</span> <span class="dv">2</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="st">"After"</span>, <span class="at">pos =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="blog1_post_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">The blue arrow (1, 0) is the original vector. The red arrow (2, 1) points in a new direction, so (1, 0) is not an eigenvector.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>One detail matters: an arrow is an eigenvector of a particular matrix. A different matrix might turn that same arrow. So the special relationship is between the arrow and the transformation we apply.</p>
</section>
<section id="what-the-formula-means" class="level2">
<h2 class="anchored" data-anchor-id="what-the-formula-means">What the formula means</h2>
<p>The definition puts this observation into one equation:</p>
<p><span class="math display">\[
Av = \lambda v, \qquad v \ne 0.
\]</span></p>
<p>Here, <span class="math inline">\(v\)</span> is an eigenvector and <span class="math inline">\(\lambda\)</span> is its eigenvalue. For this particular vector, multiplying by the matrix does the same thing as multiplying by one number.</p>
<p>An eigenvalue of one leaves the arrow unchanged. A negative eigenvalue reverses it along the same line. An eigenvalue of zero collapses it to the origin. The zero vector itself is excluded because it has no direction.</p>
</section>
<section id="so-where-do-the-turning-arrows-go" class="level2">
<h2 class="anchored" data-anchor-id="so-where-do-the-turning-arrows-go">So where do the turning arrows go?</h2>
<p>If we keep applying our matrix to <span class="math inline">\((1,0)\)</span>, we get <span class="math inline">\((2,1)\)</span>, then <span class="math inline">\((5,4)\)</span>, then <span class="math inline">\((14,13)\)</span>. The arrow gets closer to the diagonal direction of <span class="math inline">\((1,1)\)</span>. But how close, and how fast? Let’s track it. The code below applies <span class="math inline">\(A\)</span> six times and measures the angle between the arrow and the diagonal line through <span class="math inline">\((1,1)\)</span> after each step.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Angle, in degrees, between an arrow and the diagonal line through (1, 1)</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>angle_to_diagonal <span class="ot">&lt;-</span> <span class="cf">function</span>(v) {</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># size of the part along (1, 1)</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  along  <span class="ot">&lt;-</span> <span class="fu">abs</span>(v[<span class="dv">1</span>] <span class="sc">+</span> v[<span class="dv">2</span>]) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">2</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># size of the part along (1, -1)</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  across <span class="ot">&lt;-</span> <span class="fu">abs</span>(v[<span class="dv">1</span>] <span class="sc">-</span> v[<span class="dv">2</span>]) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">2</span>)  </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">atan2</span>(across, along) <span class="sc">*</span> <span class="dv">180</span> <span class="sc">/</span> pi</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>trajectory <span class="ot">&lt;-</span> <span class="fu">data.frame</span>()</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (step <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">6</span>) {</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  trajectory <span class="ot">&lt;-</span> <span class="fu">rbind</span>(trajectory,</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">data.frame</span>(<span class="at">step =</span> step, <span class="at">x =</span> v[<span class="dv">1</span>], <span class="at">y =</span> v[<span class="dv">2</span>],</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">angle =</span> <span class="fu">angle_to_diagonal</span>(v)))</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>  v <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(A <span class="sc">%*%</span> v)</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(trajectory, <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>             <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Step"</span>, <span class="st">"x"</span>, <span class="st">"y"</span>, <span class="st">"Angle to diagonal (degrees)"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">Step</th>
<th style="text-align: right;">x</th>
<th style="text-align: right;">y</th>
<th style="text-align: right;">Angle to diagonal (degrees)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">45.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">18.43</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6.34</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">2.12</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">0.71</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">122</td>
<td style="text-align: right;">121</td>
<td style="text-align: right;">0.24</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">365</td>
<td style="text-align: right;">364</td>
<td style="text-align: right;">0.08</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The angle starts at 45 degrees and drops below a tenth of a degree after just six steps. And if you look at the numbers closely, there’s a pattern. After the first step, each angle is about three times smaller than the one before it: 18.43, 6.34, 2.12, 0.71. Why three?</p>
<p>That happens because the part along the eigenvector <span class="math inline">\((1,1)\)</span> grows faster than the other part. Here’s what I mean: we can split any arrow into two pieces: one piece along <span class="math inline">\((1,1)\)</span> and one piece along the other eigenvector of <span class="math inline">\(A\)</span>, which is <span class="math inline">\((1,-1)\)</span>. For example, <span class="math inline">\((1,0)\)</span> is just half of <span class="math inline">\((1,1)\)</span> plus half of <span class="math inline">\((1,-1)\)</span>. Every time we apply <span class="math inline">\(A\)</span>, the <span class="math inline">\((1,1)\)</span> piece gets multiplied by its eigenvalue, 3, and the <span class="math inline">\((1,-1)\)</span> piece gets multiplied by its eigenvalue, 1, so it doesn’t change at all. After <span class="math inline">\(k\)</span> steps we get</p>
<p><span class="math display">\[
A^k \begin{pmatrix}1 \\ 0\end{pmatrix} = \frac{3^k}{2}\begin{pmatrix}1 \\ 1\end{pmatrix} + \frac{1}{2}\begin{pmatrix}1 \\ -1\end{pmatrix}.
\]</span></p>
<p>Every step, the <span class="math inline">\((1,1)\)</span> piece gets three times bigger compared to the other piece, so the arrow leans more and more toward the diagonal. That’s where the three comes from. It’s just the ratio of the two eigenvalues, 3 divided by 1.</p>
<p>At this point I wondered if <span class="math inline">\((1,0)\)</span> was just a lucky choice. To check, I tried sixteen arrows pointing in all different directions. I applied <span class="math inline">\(A\)</span> to each of them five times, and then shrank every arrow back to length one so we only compare directions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>directions <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">337.5</span>, <span class="at">by =</span> <span class="fl">22.5</span>) <span class="sc">*</span> pi <span class="sc">/</span> <span class="dv">180</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># one arrow per column</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>before <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="fu">cos</span>(directions), <span class="fu">sin</span>(directions))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>after <span class="ot">&lt;-</span> before</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (step <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) after <span class="ot">&lt;-</span> A <span class="sc">%*%</span> after</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># rescale to length one</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>after <span class="ot">&lt;-</span> <span class="fu">sweep</span>(after, <span class="dv">2</span>, <span class="fu">sqrt</span>(<span class="fu">colSums</span>(after<span class="sc">^</span><span class="dv">2</span>)), <span class="st">"/"</span>)  </span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="co"># the two arrows that start exactly along the other eigenvector, (1, -1)</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>on_other_line <span class="ot">&lt;-</span> <span class="fu">abs</span>(before[<span class="dv">1</span>, ] <span class="sc">+</span> before[<span class="dv">2</span>, ]) <span class="sc">&lt;</span> <span class="fl">1e-8</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>arrow_col <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(on_other_line, <span class="st">"#CD6600"</span>, <span class="st">"blue"</span>)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>panels <span class="ot">&lt;-</span> <span class="fu">list</span>(before, after)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>titles <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Before"</span>, <span class="st">"After applying A five times"</span>)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>) {</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="at">type =</span> <span class="st">"n"</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">1.1</span>, <span class="fl">1.1</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">1.1</span>, <span class="fl">1.1</span>),</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"x"</span>, <span class="at">ylab =</span> <span class="st">"y"</span>, <span class="at">asp =</span> <span class="dv">1</span>, <span class="at">main =</span> titles[i])</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"gray50"</span>)</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrows</span>(<span class="dv">0</span>, <span class="dv">0</span>, panels[[i]][<span class="dv">1</span>, ], panels[[i]][<span class="dv">2</span>, ],</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> arrow_col, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">length =</span> <span class="fl">0.08</span>)</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="blog1_post_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="768"></p>
<p></p><figcaption class="figure-caption">Left: sixteen arrows before applying A. Right: the same arrows after applying A five times, rescaled to length one. The blue arrows all end up on the dashed diagonal line. The two orange arrows start on the line through (1, -1) and stay there.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>It wasn’t luck. Fourteen of the sixteen arrows end up on the diagonal line. Some point toward <span class="math inline">\((1,1)\)</span> and some toward <span class="math inline">\((-1,-1)\)</span>, but it’s the same line. The only two that don’t are the orange ones. An arrow starting exactly along the other eigenvector, <span class="math inline">\((1,-1)\)</span>, would stay unchanged instead, because its eigenvalue is 1. But these two only survive because they start exactly on that line. If you push one of them even a tiny bit off of it, that tiny piece along <span class="math inline">\((1,1)\)</span> gets tripled every step, and eventually it takes over too.</p>
</section>
<section id="does-it-matter-how-far-apart-the-eigenvalues-are" class="level2">
<h2 class="anchored" data-anchor-id="does-it-matter-how-far-apart-the-eigenvalues-are">Does it matter how far apart the eigenvalues are?</h2>
<p>If the three really comes from dividing the two eigenvalues, then the speed should change when the eigenvalues get closer together. I wanted to check this, so I made a second matrix, <span class="math inline">\(B\)</span>. It has the same eigenvectors as <span class="math inline">\(A\)</span>, and its biggest eigenvalue is still 3. The only difference is that its other eigenvalue is 2.7 instead of 1:</p>
<p><span class="math display">\[
B = \begin{pmatrix}2.85 &amp; 0.15 \\ 0.15 &amp; 2.85\end{pmatrix}.
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fl">2.85</span>, <span class="fl">0.15</span>, <span class="fl">0.15</span>, <span class="fl">2.85</span>), <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">eigen</span>(A)<span class="sc">$</span>values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eigen</span>(B)<span class="sc">$</span>values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.0 2.7</code></pre>
</div>
</div>
<p>R confirms it: <span class="math inline">\(A\)</span> has eigenvalues 3 and 1, and <span class="math inline">\(B\)</span> has 3 and 2.7. Now let’s start both matrices from <span class="math inline">\((1,0)\)</span>, apply each one 40 times, and watch the angle.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>track_angle <span class="ot">&lt;-</span> <span class="cf">function</span>(M, v, n_steps) {</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  angles <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n_steps <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (k <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span>n_steps) {</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    angles[k <span class="sc">+</span> <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">angle_to_diagonal</span>(v)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    v <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(M <span class="sc">%*%</span> v)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  angles</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>steps <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">40</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>angle_A <span class="ot">&lt;-</span> <span class="fu">track_angle</span>(A, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>), <span class="dv">40</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>angle_B <span class="ot">&lt;-</span> <span class="fu">track_angle</span>(B, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>), <span class="dv">40</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="co"># First step at which the arrow is within one degree of the diagonal</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">A =</span> <span class="fu">min</span>(steps[angle_A <span class="sc">&lt;</span> <span class="dv">1</span>]), <span class="at">B =</span> <span class="fu">min</span>(steps[angle_B <span class="sc">&lt;</span> <span class="dv">1</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> A  B 
 4 39 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(steps, angle_B, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">45</span>),</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Number of times the matrix is applied"</span>,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Angle to diagonal (degrees)"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(steps, angle_A, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"gray50"</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">2.3</span>, <span class="fl">7.5</span>, <span class="st">"A"</span>, <span class="at">pos =</span> <span class="dv">4</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">12</span>, <span class="dv">19</span>, <span class="st">"B"</span>, <span class="at">pos =</span> <span class="dv">4</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"A: eigenvalues 3 and 1"</span>, <span class="st">"B: eigenvalues 3 and 2.7"</span>),</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"red"</span>), <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">bty =</span> <span class="st">"n"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="blog1_post_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">How far the arrow is from the diagonal after each step, starting from (1, 0). The dashed line marks one degree. A gets there after 4 steps, while B needs 39.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>This was the part that surprised me the most. Both matrices stretch <span class="math inline">\((1,1)\)</span> by exactly 3, so if you only looked at the biggest eigenvalue, you would think they behave the same. They don’t. With <span class="math inline">\(A\)</span>, the arrow is within one degree of the diagonal after 4 steps. With <span class="math inline">\(B\)</span>, it takes 39 steps, almost ten times longer. The reason is the same as before: each step, the <span class="math inline">\((1,1)\)</span> piece gains on the other piece by the ratio of the eigenvalues. For <span class="math inline">\(A\)</span> that ratio is <span class="math inline">\(3/1 = 3\)</span>, but for <span class="math inline">\(B\)</span> it is only <span class="math inline">\(3/2.7 \approx 1.11\)</span>. That’s why, with <span class="math inline">\(B\)</span>, the arrow keeps “remembering” where it started for so long.</p>
</section>
<section id="what-i-learned-from-this" class="level2">
<h2 class="anchored" data-anchor-id="what-i-learned-from-this">What I learned from this</h2>
<p>Eigenvectors show us special directions within a transformation. Eigenvalues tell us what happens along those directions. Together, they make it easier to understand how a system changes over time. That’s the textbook summary, and it’s true, but it felt pretty abstract to me until I actually ran these experiments. Two things finally clicked.</p>
<p>The first is that eigenvectors are not just weird exceptions. I used to think of them as the few arrows that happen not to turn. But if you apply the same matrix again and again, almost every arrow ends up lining up with the eigenvector that has the biggest eigenvalue. So the eigenvector is basically telling you where everything is heading. I think this is why eigenvectors show up in Markov chains and PageRank. In both cases, what we care about is where a process ends up after many steps, and that answer is an eigenvector. Even for PCA, one classic way to find the first principal component, called the power method, uses the same trick of multiplying by a matrix (the covariance matrix) over and over.</p>
<p>The second is that computing the eigenvalues isn’t enough. We should also compare them. The biggest eigenvalue tells us which direction wins in the end, but how close the second one is to the biggest tells us how long that takes. With 3 and 1 it took 4 steps; with 3 and 2.7 it took 39. I find it helpful to think about this with a labor market example. In a simple model where workers move between having a job and being unemployed each month, this ratio decides whether a jump in unemployment fades in a few months or sticks around for a long time.</p>
<p>One thing we need to be careful about, though: this only works when one eigenvalue is strictly bigger in size than all the others. For example, a matrix that rotates every arrow by 90 degrees has no real eigenvectors at all, so the arrows just keep spinning around and never settle on any line.</p>
<p>So, back to my question. The few arrows that don’t turn matter because they tell us where all the other arrows are going, and the eigenvalues tell us how fast they get there. For me, that’s a much more useful way to think about eigenvectors than just remembering <span class="math inline">\(Av = \lambda v\)</span>.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left"><img src="../../../images/UniversityofPennsylvania_FullLogo_RGB.png" class="img-fluid" width="100"></div>   
      <div class="nav-footer-center">© 2026 Michael Li</div>
  </div>
</footer>



</body></html>